import {
  CORE_ASSIGNABLE_ENTITY_TYPE_ENUM,
  CORE_COMPLETION_ENTITY_TYPE_ENUM,
  CORE_DIRECT_REVIEW_ENTITY_TYPE_ENUM,
  CORE_ENTITY_TYPE_ENUM,
  CORE_LIFECYCLE_ENTITY_TYPE_ENUM
} from './entity-registry'

export const APPROVAL_TYPE_ENUM = [
  'fundingcasereview',
  'fundingclaimreview',
  'fundingcaseforecast',
  'fundingcasepayment'
] as const

export const STREAM_ASSESSMENT_CHECKLIST_TYPE_ENUM = [
  'applicantrecipientriskassessment',
  'fundingagreementriskassessment',
  'fundingcaseawardassessment'
] as const
export const LANGUAGE_PREFERENCE_ENUM = ['eng', 'fra'] as const
export const REVIEW_TYPE_ENUM = ['checklist', 'assessment'] as const
export const ENTITY_TYPE_ENUM = CORE_ENTITY_TYPE_ENUM
export const SCOPE_ENTITY_TYPE_ENUM = [
  'fundingopportunity',
  'fundingcaseintake',
  'fundingcaseagreement',
  'applicantrecipient',
  'transferpaymentstream'
] as const
export const EXECUTION_ENTITY_TYPE_ENUM = [
  'fundingcaseagreement',
  'fundingcaseagreementcloseout',
  'applicantrecipient',
  'commonreview',
  'commonrecommendation',
  'fundingcaseintake',
  'fundingcaseagreementclaim',
  'fundingcaseamendment',
  'fundingcasemonitor',
  'fundingclaimreconcile',
  'fundingcaseforecast',
  'fundingcasepayment',
  'fundingcaserecommendation',
  'fundingcaseagreementcommitment'
] as const
export const COMPLETION_ENTITY_TYPE_ENUM = CORE_COMPLETION_ENTITY_TYPE_ENUM
export const REVIEW_TARGET_ENTITY_TYPE_ENUM = CORE_DIRECT_REVIEW_ENTITY_TYPE_ENUM
export const RECOMMENDATION_EXECUTION_ENTITY_TYPE_ENUM = [
  'commonreview',
  'fundingcaseagreement',
  'fundingcaseagreementcloseout',
  'fundingcaseagreementclaim',
  'fundingcaseamendment',
  'fundingcasemonitor',
  'fundingclaimreconcile',
  'fundingcaseforecast',
  'fundingcasepayment',
  'fundingcaseagreementcommitment'
] as const
export const DEFAULT_TRANSFER_PAYMENT_ENTITY_TYPE = 'fundingcasepayment' as const

export type CommonEntityType = (typeof ENTITY_TYPE_ENUM)[number]
export type ScopeEntityType = (typeof SCOPE_ENTITY_TYPE_ENUM)[number]
export type ExecutionEntityType = (typeof EXECUTION_ENTITY_TYPE_ENUM)[number]
export type CompletionEntityType = (typeof COMPLETION_ENTITY_TYPE_ENUM)[number]
export type ReviewTargetEntityType = (typeof REVIEW_TARGET_ENTITY_TYPE_ENUM)[number]
export type RecommendationExecutionEntityType = (typeof RECOMMENDATION_EXECUTION_ENTITY_TYPE_ENUM)[number]

export const WORKFLOW_TARGET_ENTITY_TYPE_ENUM = CORE_LIFECYCLE_ENTITY_TYPE_ENUM
export type WorkflowTargetEntityType = (typeof WORKFLOW_TARGET_ENTITY_TYPE_ENUM)[number]

export const ASSIGNABLE_ENTITY_TYPE_ENUM = CORE_ASSIGNABLE_ENTITY_TYPE_ENUM
export type AssignableEntityType = (typeof ASSIGNABLE_ENTITY_TYPE_ENUM)[number]

export const AMENDED_TYPE_ENUM = ['articles', 'activities', 'budget', 'duration', 'other'] as const
export const AGREEMENT_TYPE_ENUM = ['grant', 'nonrepayable', 'repayable', 'partiallyrepayable', 'other'] as const
export const APPLICANT_RECIPIENT_TYPE_ENUM = [
  'aboriginalrecipients',
  'forprofitorganizations',
  'government',
  'internationalnongov',
  'notforprofitorganizationsandcharities',
  'other',
  'individualorsoleproprietorships',
  'academia'
] as const

export const REGISTRY_TYPE_ENUM = [
  'provincialbusinessnumber',
  'federalbusinessnumber',
  'craprogramaccountnumber',
  'noc',
  'naics',
  'other'
] as const
export type RegistryType = (typeof REGISTRY_TYPE_ENUM)[number]
export const JURISDICTION_ENUM = ['ab', 'bc', 'mb', 'nb', 'nl', 'ns', 'nt', 'nu', 'on', 'pe', 'qc', 'sk', 'yt'] as const

export const AGREEMENT_APPLICANT_RECIPIENT_TYPE_ENUM = ['guarantor', 'obligant', 'consultant', 'partner'] as const
export const FUNDING_OPPORTUNITY_ASSESSMENT_CHECKLIST_TYPE_ENUM = [
  'fundingopportunitypreaward',
  'fundingopportunityaward',
  'fundingopportunityriskassessment'
] as const
export const DECISION_TYPES_ENUM = ['fundingcaseintakeassessment'] as const
export const PAYMENT_TYPE_ENUM = ['reimbursement', 'advance'] as const
export const ACTION_TYPE_ENUM = ['amendment', 'mandatoryaction', 'suggestedaction', 'none'] as const
export const RESPONSIBLE_PARTY_ENUM = ['applicantrecipient', 'organization', 'joint'] as const
export const MONITOR_ACTION_TYPE_ENUM = ACTION_TYPE_ENUM
export const MONITOR_RESPONSIBLE_PARTY_ENUM = RESPONSIBLE_PARTY_ENUM
export const FOLLOW_UP_STATUS_ENUM = ['open', 'onhold', 'completed', 'cancelled', 'unabletocomplete'] as const

export const CURRENCY_CODES_ENUM = [
  'all',
  'amd',
  'ang',
  'aoa',
  'ars',
  'aud',
  'awg',
  'azn',
  'bam',
  'bbd',
  'bdt',
  'bgn',
  'bhd',
  'bif',
  'bnd',
  'bob',
  'bov',
  'brl',
  'bsd',
  'btn',
  'bwp',
  'byr',
  'bzd',
  'cad',
  'cdf',
  'chf',
  'clf',
  'clp',
  'cny',
  'cop',
  'crc',
  'cuc',
  'cve',
  'czk',
  'djf',
  'dkk',
  'dop',
  'dzd',
  'egp',
  'ern',
  'etb',
  'eur',
  'fjd',
  'gbp',
  'gel',
  'gip',
  'gmd',
  'gnf',
  'gtq',
  'gyd',
  'hkd',
  'hnl',
  'hrk',
  'htg',
  'huf',
  'idr',
  'ils',
  'inr',
  'iqd',
  'irr',
  'isk',
  'jmd',
  'jod',
  'jpy',
  'kes',
  'kgs',
  'khr',
  'kmf',
  'krw',
  'kwd',
  'kyd',
  'kzt',
  'lak',
  'lbp',
  'lrd',
  'lsl',
  'lyd',
  'mga',
  'mkd',
  'mop',
  'mur',
  'mvr',
  'mwk',
  'myr',
  'nok',
  'nzd',
  'svc',
  'usd',
  'xaf',
  'xcd',
  'xdr',
  'xof',
  'xpf',
  'zar'
] as const

export const COUNTRIES_ENUM = [
  'ad',
  'ae',
  'af',
  'ag',
  'ai',
  'al',
  'am',
  'ao',
  'aq',
  'ar',
  'as',
  'at',
  'au',
  'aw',
  'ax',
  'az',
  'ba',
  'bb',
  'bd',
  'be',
  'bf',
  'bg',
  'bh',
  'bi',
  'bj',
  'bl',
  'bm',
  'bn',
  'bo',
  'bq',
  'br',
  'bs',
  'bt',
  'bv',
  'bw',
  'by',
  'bz',
  'ca',
  'cc',
  'cd',
  'cf',
  'cg',
  'ch',
  'ci',
  'ck',
  'cl',
  'cm',
  'cn',
  'co',
  'cr',
  'cu',
  'cv',
  'cw',
  'cx',
  'cy',
  'cz',
  'de',
  'dj',
  'dk',
  'dm',
  'do',
  'dz',
  'ec',
  'ee',
  'eg',
  'eh',
  'er',
  'es',
  'et',
  'fi',
  'fj',
  'fk',
  'fm',
  'fo',
  'fr',
  'ga',
  'gb',
  'gd',
  'ge',
  'gf',
  'gg',
  'gh',
  'gi',
  'gl',
  'gm',
  'gn',
  'gp',
  'gq',
  'gr',
  'gs',
  'gt',
  'gu',
  'gw',
  'gy',
  'hk',
  'hm',
  'hn',
  'hr',
  'ht',
  'hu',
  'id',
  'ie',
  'il',
  'im',
  'in',
  'io',
  'iq',
  'ir',
  'is',
  'it',
  'je',
  'jm',
  'jo',
  'jp',
  'ke',
  'kg',
  'kh',
  'ki',
  'km',
  'kn',
  'kp',
  'kr',
  'kw',
  'ky',
  'kz',
  'la',
  'lb',
  'lc',
  'li',
  'lk',
  'lr',
  'ls',
  'lt',
  'lu',
  'lv',
  'ly',
  'ma',
  'mc',
  'md',
  'me',
  'mf',
  'mg',
  'mh',
  'mk',
  'ml',
  'mm',
  'mn',
  'mo',
  'mp',
  'mq',
  'mr',
  'ms',
  'mt',
  'mu',
  'mv',
  'mw',
  'mx',
  'my',
  'mz',
  'na',
  'nc',
  'ne',
  'nf',
  'ng',
  'ni',
  'nl',
  'no',
  'np',
  'nr',
  'nu',
  'nz',
  'om',
  'pa',
  'pe',
  'pf',
  'pg',
  'ph',
  'pk',
  'pl',
  'pm',
  'pn',
  'pr',
  'ps',
  'pt',
  'pw',
  'py',
  'qa',
  're',
  'ro',
  'rs',
  'ru',
  'rw',
  'sa',
  'sb',
  'sc',
  'sd',
  'se',
  'sg',
  'sh',
  'si',
  'sj',
  'sk',
  'sl',
  'sm',
  'sn',
  'so',
  'sr',
  'ss',
  'st',
  'sv',
  'sx',
  'sy',
  'sz',
  'tc',
  'td',
  'tf',
  'tg',
  'th',
  'tj',
  'tk',
  'tl',
  'tm',
  'tn',
  'to',
  'tr',
  'tt',
  'tv',
  'tw',
  'tz',
  'ua',
  'ug',
  'um',
  'us',
  'uy',
  'uz',
  'va',
  'vc',
  've',
  'vg',
  'vi',
  'vn',
  'vu',
  'wf',
  'ws',
  'ye',
  'yt',
  'za',
  'zm',
  'zw'
] as const
