import { Worker } from 'node:worker_threads'
import { dirname, resolve } from 'node:path'
import { pathToFileURL } from 'node:url'

export const ADMIN_SQL_DUMP_TIMEOUT_ERROR = 'Admin SQL dump worker timed out'
export const ADMIN_SQL_DUMP_ABORT_ERROR = 'Admin SQL dump request was aborted'
export const DEFAULT_ADMIN_SQL_DUMP_TIMEOUT_MS = 30_000

interface AdminSqlDumpWorkerSuccess {
  ok: true
  sql: string
}

interface AdminSqlDumpWorkerFailure {
  error: string
  ok: false
}

interface RunAdminSqlDumpOptions {
  signal?: AbortSignal
  timeoutMs?: number
  workerFactory?: () => Worker
}

type AdminSqlDumpWorkerMessage = AdminSqlDumpWorkerFailure | AdminSqlDumpWorkerSuccess

let activeAdminSqlDump: Promise<string> | null = null

/**
 * Resolves the source module or emitted worker used by the runtime.
 *
 * @param nodeEnv - Runtime environment name.
 * @param repositoryRoot - Explicit source workspace root for development.
 * @param runtimeEntryPath - Packaged server entry path for production.
 * @param devWorkerPath - Explicit worker bundle produced from the source entry in development.
 * @returns URL that the Node worker can execute.
 */
export const resolveAdminSqlDumpWorkerUrl = (
  nodeEnv: string | undefined = process.env.NODE_ENV,
  repositoryRoot: string = process.cwd(),
  runtimeEntryPath: string | undefined = process.argv[1],
  devWorkerPath: string | undefined = process.env.GCS_DEV_ADMIN_SQL_DUMP_WORKER_PATH
): URL => {
  if (nodeEnv === 'production') {
    if (runtimeEntryPath === undefined || runtimeEntryPath.trim() === '') {
      throw new Error('Runtime entry path is unavailable for the packaged admin SQL dump worker')
    }
    return pathToFileURL(resolve(dirname(runtimeEntryPath), 'admin-sql-dump-worker.mjs'))
  }

  if (devWorkerPath === undefined || devWorkerPath.trim() === '') {
    throw new Error(`Development admin SQL dump worker is unavailable for repository ${repositoryRoot}`)
  }
  return pathToFileURL(resolve(repositoryRoot, devWorkerPath))
}

/**
 * Validates the discriminated response returned by the worker.
 *
 * @param value - Untrusted worker response.
 * @returns Whether the value is a valid worker message.
 */
const isAdminSqlDumpWorkerMessage = (value: unknown): value is AdminSqlDumpWorkerMessage => {
  if (typeof value !== 'object' || value === null || !('ok' in value)) {
    return false
  }

  if (value.ok === true) {
    return 'sql' in value && typeof value.sql === 'string'
  }
  return value.ok === false && 'error' in value && typeof value.error === 'string'
}

/**
 * Creates one isolated worker without passing request-controlled arguments.
 *
 * @returns Worker that generates one dump.
 */
export const createAdminSqlDumpWorker = (): Worker => new Worker(resolveAdminSqlDumpWorkerUrl())

/**
 * Runs one bounded worker and waits for its resources to terminate.
 *
 * @param workerFactory - Factory for the isolated worker.
 * @param timeoutMs - Maximum worker execution duration.
 * @returns SQL generated by the worker.
 */
const executeAdminSqlDumpWorker = async (
  workerFactory: () => Worker,
  timeoutMs: number
): Promise<string> => {
  const worker = workerFactory()

  return await new Promise<string>((resolveDump, rejectDump) => {
    let settled = false
    const timer = setTimeout(() => {
      void finish(new Error(ADMIN_SQL_DUMP_TIMEOUT_ERROR))
    }, timeoutMs)

    /**
     * Removes listeners, terminates the worker, then settles the result.
     *
     * @param result - SQL text or stable failure.
     */
    const finish = async (result: Error | string): Promise<void> => {
      if (settled) {
        return
      }
      settled = true
      clearTimeout(timer)
      worker.off('message', handleMessage)
      worker.off('error', handleError)
      worker.off('exit', handleExit)
      try {
        await worker.terminate()
      } catch (error: unknown) {
        rejectDump(new Error(
          `Admin SQL dump worker cleanup failed: ${error instanceof Error ? error.message : String(error)}`
        ))
        return
      }
      if (result instanceof Error) {
        rejectDump(result)
      } else {
        resolveDump(result)
      }
    }

    /**
     * Handles and validates the worker protocol response.
     *
     * @param message - Untrusted worker message.
     */
    const handleMessage = (message: unknown): void => {
      if (!isAdminSqlDumpWorkerMessage(message)) {
        void finish(new Error('Admin SQL dump worker returned an invalid response'))
      } else if (message.ok) {
        void finish(message.sql)
      } else {
        void finish(new Error(`Admin SQL dump worker failed: ${message.error}`))
      }
    }
    /**
     * Converts a worker runtime error into a stable service error.
     *
     * @param error - Worker runtime failure.
     * @returns Nothing.
     */
    const handleError = (error: Error): void => void finish(new Error(
      `Admin SQL dump worker failed: ${error.message}`
    ))
    /**
     * Converts an early worker exit into a stable service error.
     *
     * @param code - Worker exit code.
     * @returns Nothing.
     */
    const handleExit = (code: number): void => void finish(new Error(
      `Admin SQL dump worker exited before returning a result (code ${String(code)})`
    ))
    worker.once('message', handleMessage)
    worker.once('error', handleError)
    worker.once('exit', handleExit)
  })
}

/**
 * Lets one caller stop waiting without cancelling a shared dump for other callers.
 *
 * @param dump - Shared dump operation.
 * @param signal - Optional request lifecycle signal.
 * @returns Dump result while the caller remains connected.
 */
const waitForAdminSqlDump = async (
  dump: Promise<string>,
  signal: AbortSignal | undefined
): Promise<string> => {
  if (signal === undefined) {
    return await dump
  }
  if (signal.aborted) {
    throw new Error(ADMIN_SQL_DUMP_ABORT_ERROR)
  }

  return await new Promise<string>((resolveDump, rejectDump) => {
    const abort = (): void => rejectDump(new Error(ADMIN_SQL_DUMP_ABORT_ERROR))
    signal.addEventListener('abort', abort, { once: true })
    void dump.then(resolveDump, rejectDump).finally(() => {
      signal.removeEventListener('abort', abort)
    })
  })
}

/**
 * Generates an admin SQL export using one process-wide in-flight worker.
 *
 * @param options - Timeout, request signal, and test worker factory.
 * @returns SQL dump text.
 */
export const runAdminSqlDump = async (
  options: RunAdminSqlDumpOptions = {}
): Promise<string> => {
  if (activeAdminSqlDump === null) {
    const workerFactory = options.workerFactory ?? createAdminSqlDumpWorker
    const timeoutMs = options.timeoutMs ?? DEFAULT_ADMIN_SQL_DUMP_TIMEOUT_MS
    activeAdminSqlDump = executeAdminSqlDumpWorker(workerFactory, timeoutMs)
    void activeAdminSqlDump.finally(() => {
      activeAdminSqlDump = null
    }).catch(() => {})
  }

  return await waitForAdminSqlDump(activeAdminSqlDump, options.signal)
}
